project/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),

    url(r"^", include("cms.urls")),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cms_plugins/gallery/models.py
from django.db import models
from cms.models import CMSPlugin, Page


GALLERY_TYPES = (("gallery", "Gallery"), ("slider", "Slider"), )


class Gallery(models.Model):
    gallery_type = models.CharField(max_length=64, choices=GALLERY_TYPES)
    name = models.CharField(max_length=255)

    def __unicode__(self):
        return u"%s (%s)" % (self.name, self.gallery_type)

class Image(models.Model):
    gallery = models.ForeignKey(Gallery)
    img = models.ImageField(upload_to="cmsweb/image/img")

class GalleryPluginX(CMSPlugin):
    gallery = models.ForeignKey(Gallery)

    def __unicode__(self):
        return u"%s ~%i" % (self.gallery.name, self.gallery.pk)

cms_plugins/gallery/templates/cms_plugins/gallery.html
<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}cms_plugins/cmsplugins-bootstrap-positions.css">

{% if object.gallery_type == "slider" %}
<script src="{{STATIC_URL}}responsiveslider/responsiveslides.min.js"></script>
<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}responsiveslider/rslides.css">
<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}responsiveslider/rslides2.css">
    <div class="rslides_container hspace">
    <ul class="a{{random}}_rslides rslides">
        {% for img in object.image_set.all %}
            <li><img src="{{img.img.url}}"></li>
        {% endfor %}
    </ul>
    </div>


    <script type="text/javascript">
        jQuery(document).ready(function($) {
            $('.a{{random}}_rslides').responsiveSlides({
                auto: false,
                pager: true,
                nav: true,
                speed: 500,
                maxwidth: 800,
                namespace: "centered-btns"
            });
        });
    </script>
{% else %}
    <style type="text/css">
    .cmsweb-gallery div {
        margin: 0 5px 5px 0;
    }

    /* Bootstrap img */
    img {
      width: auto\9;
      height: auto;
      max-width: 100%;
      vertical-align: middle;
      border: 0;
      -ms-interpolation-mode: bicubic;
    }
    </style>

    <link rel="stylesheet" href="{{STATIC_URL}}lightbox/css/lightbox.css" type="text/css" media="screen" />

    <div class="cmsplugins-row-fluid cmsweb-gallery hspace">
        {% for img in object.image_set.all %}
            <div class="cmsplugins-span4" style="margin-left:0;">
                <a href="{{img.img.url}}" rel="lightbox[gallery]"><img src="{{img.img.url}}"></a>
            </div>
        {% endfor %}
    </div>

    <script type="text/javascript">
    var url_prefix = "{{STATIC_URL}}lightbox/";
    </script>

    <script src="{{STATIC_URL}}lightbox/js/jquery-1.7.2.min.js"></script>
    <script src="{{STATIC_URL}}lightbox/js/jquery-ui-1.8.18.custom.min.js"></script>
    <script src="{{STATIC_URL}}lightbox/js/jquery.smooth-scroll.min.js"></script>
    <script src="{{STATIC_URL}}lightbox/js/lightbox.js"></script>

    <script type="text/javascript">
        jQuery(document).ready(function($) {
            $('a').smoothScroll({
                speed: 1000,
                easing: 'easeInOutCubic'
            });
        });
    </script>
{% endif %}

point_template/templates/cms/plugins/teaser.html
{% load i18n %}
<h3 style="line-height: 1.1em;">{% if link %}<a href="{{ link }}">{% endif %}{{ object.title }}{% if link %}</a>{% endif %}</h3>

<table style="margin-bottom:20px;"><tr><td style="width:110px">
{% if object.image %}
            {% if link %}<a href="{{ link }}">{% endif %}
                <img src="{{ object.image.url }}" alt="{{ object.title }}" style="margin-right:10px";/>
            {% if link %}</a>{% endif %}
        {% endif %}
</td><td>
     {% if object.description %}
<p>{{ object.description }}</p>

{% endif %}
{% if link %}<a href="{{ link }}">{% trans "more" %} &#187;</a>{% endif %}
</td></tr></table>

point_template/templates/cmstemplate/point/base.html
<!DOCTYPE html>
{% load cms_tags menu_tags sekizai_tags %}
<html lang="en">
<head>
  <meta name="description" content="{% page_attribute meta_description %}"/>
    <meta name="keywords" content="{% page_attribute meta_keywords %}"/>
<title>{% page_attribute "page_title" %}</title>
<meta charset="utf-8">
<link rel="stylesheet" href="/static/static/cmstemplate/point/css/reset.css" type="text/css" media="screen">
<link rel="stylesheet" href="/static/static/cmstemplate/point/css/style.css" type="text/css" media="screen">
<link rel="stylesheet" href="/static/static/cmstemplate/point/css/layout.css" type="text/css" media="screen">
<link rel="stylesheet" href="/static/static/bootstrap-positions.css" type="text/css" media="screen">
<link rel="stylesheet" href="/static/static/bootstrap-forms.css" type="text/css" media="screen">

<script type="text/javascript" src="/static/static/cmstemplate/point/js/jquery-1.6.min.js"></script>
<script type="text/javascript" src="/static/static/cmstemplate/point/js/tms-0.3.js"></script>
<script type="text/javascript" src="/static/static/cmstemplate/point/js/tms_presets.js"></script> 
<script type="text/javascript" src="/static/static/cmstemplate/point/js/jquery.easing.1.3.js"></script> 
<script src="/static/static/cmstemplate/point/js/FF-cash.js" type="text/javascript"></script>
<!--[if lt IE 7]>
  <div style=' clear: both; text-align:center; position: relative;'>
    <a href="/static/static/cmstemplate/point/http://www.microsoft.com/windows/internet-explorer/default.aspx?ocid=ie6_countdown_bannercode"><img src="/static/static/cmstemplate/point/http://www.theie6countdown.com/images/upgrade.jpg" border="0"  alt="" /></a>
  </div>
<![endif]-->
<!--[if lt IE 9]>
  <script type="text/javascript" src="/static/static/cmstemplate/point/js/html5.js"></script>
  <link rel="stylesheet" href="/static/static/cmstemplate/point/css/ie.css" type="text/css" media="screen">
<![endif]-->
{% render_block "css" %}
{%block html_head%}{%endblock html_head%}

<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-36606689-1']);
  _gaq.push(['_setDomainName', 'petrsika.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
<style>
.field label {
    margin-bottom: 10px;
}
</style>

</head>
<body id="page1">
  {% cms_toolbar %}
<!-- header -->
  <div class="bg">
    <div class="main">
      <header>
        <div class="row-1">
          <div class="row">
            <div class="span8" style="margin-left:0;margin-top:20px">
              <h1 style="color: white; font-size: 30px; margin-bottom: 10px;">Ing.Petr Šika</h1>
              <p style="color:white;">
                Specialista na inkluzivní mobilitu seniorů a handicapovaných osob
              <br></p>
            </div>
          </div>
        </div>
        <div class="row-2" style="margin-bottom:-1px;">
          <nav>
            <ul class="menu">
              {% show_menu 0 0 0 1 %}
            </ul>
          </nav>
        </div>
        <div class="row-3">
            <div class="padding" style="margin-bottom:5px;background-color:white;color:black;padding:15px;">
              <div class="row-fluid">
                {%block header %}{%endblock header%}
              </div>
            </div>
        </div>
      </header>
<!-- content -->
      <section id="content">
        {% block adbar %}
        <div class="box-bg margin-bot">
            <div class="wrapper">
              <div class="col-1">
                <div class="box first">
                  <div class="pad">
                    <div class="wrapper indent-bot">
                      <a href="/cs/omne/"  style="text-decoration:none;">
                      <div class="extra-wrap">
                        <h3 class="color-1"><strong>Informace</strong>o mně</h3>
                      </div>
                    </div>
                    <div class="wrapper">
                      <a class="button img-indent-r" href="/cs/omne/">>></a>
                      <div class="extra-wrap">
                        Moje profesní CV,<br>pedagogická praxe<br>v akademickém prostředí
                      </div>
                    </div>
                    </a>
                  </div>
                </div>
              </div>
              <div class="col-1">
                <div class="box second">
                  <div class="pad">
                    <div class="wrapper indent-bot">
                      <a href="http://eshop.petrsika.com" style="text-decoration:none;">
                      <div class="extra-wrap">
                        <h3 class="color-2"><strong>Navštivte můj</strong>e-shop</h3>
                      </div>
                    </div>
                    <div class="wrapper">
                      <a class="button img-indent-r" href="http://eshop.petrsika.com"></a>
                      <div class="extra-wrap">
                        tištěné publikace,<br>audio publikace<br>a video publikace
                      </div>
                    </a>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-2">
                <div class="box third">
                  <div class="pad">
                    <div class="wrapper indent-bot">
                      <a href="/cs/kontakt/" style="text-decoration:none;">
                      <div class="extra-wrap">
                        <h3 class="color-3"><strong>Kontaktujte</strong>mě zde</h3>
                      </div>
                    </div>
                    <div class="wrapper">
                      <a class="button img-indent-r" href="/cs/kontakt/">>></a>
                      <div class="extra-wrap">
                        Odešlete nezávaznou termínovou a cenovou poptávku
                      </div>
                    </div>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>

        {% endblock adbar %}

        <div class="padding">
            <div class="wrapper" style="color:black;">
              <div class="row-fluid">
                {%block base_content%}
                  {%block content%}{%endblock content%}
                {%endblock base_content%}
              </div>
            </div>
        </div>
      </section>
<!-- footer -->
      <footer>
       
              {% block base_footer %}
               <div class="row-top"><div class="row-padding"><div class="wrapper">

<div class="row-fluid" style="margin-bottom: 10px">
  <div class="span2">
   <a href="/">News & Events</a>
</div>
  <div class="span2">
   <a href="/cs/pedagogicka-cinnost/">pedagogická činnost</a>
  </div>
  <div class="span2">
   <a href="/cs/vedecka-cinnost/">vědecká činnost</a>
  </div>
  <div class="span2">
   <a href="/cs/sluzby/">služby</a>
  </div>  
  <div class="span2">
   <a href="/cs/autorske-porady/">autorské pořady</a>
  </div>  
</div>

<div class="row-fluid">
  <div class="span2">
   <a href="https://www.facebook.com/pages/petrsikacom/431720616900516" target="blank"><img src="/static/static/ico70-70/fb-ico.jpg"></a>
</div>
  <div class="span2">
   <a href="https://twitter.com/petr_sika" target="blank"><img src="/static/static/ico70-70/tw-ico.jpg"></a>
  </div>
  <div class="span2">
   <a href="https://plus.google.com/u/0/117345370290886960722/posts" target="blank"><img src="/static/static/ico70-70/google-ico.jpg"></a>
  </div>
  <div class="span2">
   <a href="mailto:sika.petr@gmail.com" target="blank"><img src="/static/static/ico70-70/mail-ico.jpg"></a>
  </div>  
</div>
<br>
<center>2014 &copy; petrsika.com, všechna práva vyhrazena</center>
            </div></div></div>

              {%endblock%}
            
        <div class="row-bot">
          <div class="aligncenter">
            <!-- <p class="p0"><a rel="nofollow" href="/static/static/cmstemplate/point/http://www.templatemonster.com/" target="_blank">Website Template</a> by TemplateMonster.com | <a rel="nofollow" href="/static/static/cmstemplate/point/http://www.html5xcss3.com/" target="_blank">html5xcss3.com<a/></p>
            <a href="/static/static/cmstemplate/point/http://www.templates.com/product/3d-models/" target="_blank">3D Models</a> provided by Templates.com<br> -->
{#            <p>2013 &copy; <a href="/">Senioři bez bariér</a> | <a href="http://petrsika.com">Petr Sika</a></p>#}
            <!-- {%FOOTER_LINK} -->
          </div>
        </div>
      </footer>
    </div>
  </div>
  <script type="text/javascript">
    $(function(){
      $('.slider')._TMS({
        prevBu:'.prev',
        nextBu:'.next',
        playBu:'.play',
        duration:800,
        easing:'easeOutQuad',
        preset:'simpleFade',
        pagination:false,
        slideshow:3000,
        numStatus:false,
        pauseOnHover:true,
        banners:true,
        waitBannerAnimation:false,
        bannerShow:function(banner){
          banner
            .hide()
            .fadeIn(500)
        },
        bannerHide:function(banner){
          banner
            .show()
            .fadeOut(500)
        }
      });
    })
  </script>
  {% render_block "js" %}
</body>
</html>

point_template/templates/cmstemplate/point/footer.html
 <div class="row-top">
          <div class="row-padding">
            <div class="wrapper">





<div class="col-1">
                <h4>Address:</h4>
                <dl class="address">
                  <dt><span>Country:</span>USA</dt>
                  <dd><span>City:</span>San Diego</dd>
                  <dd><span>Address:</span>Beach st. 54</dd>
                  <dd><span>Email:</span><a href="/static/static/cmstemplate/point/#">lcenter@mail.com</a></dd>
                </dl>
              </div>
              <div class="col-2">
                <h4>Follow Us:</h4>
                <ul class="list-services">
                  <li class="item-1"><a href="/static/static/cmstemplate/point/#">Facebook</a></li>
                  <li class="item-2"><a href="/static/static/cmstemplate/point/#">Twitter</a></li>
                  <li class="item-3"><a href="/static/static/cmstemplate/point/#">LinkedIn</a></li>
                </ul>
              </div>
              <div class="col-3">
                <h4>Why Us:</h4>
                <ul class="list-1">
                  <li><a href="/static/static/cmstemplate/point/#">Lorem ipsum dolor</a></li>
                  <li><a href="/static/static/cmstemplate/point/#">Aonsect adipisic</a></li>
                  <li><a href="/static/static/cmstemplate/point/#">Eiusmjkod tempor</a></li> 
                  <li><a href="/static/static/cmstemplate/point/#">Incididunt ut labore</a></li>
                </ul>
              </div>
              <div class="col-4">
                <div class="indent3">
                  <strong class="footer-logo">Point.<strong>co</strong></strong>
                  <strong class="phone"><strong>Toll Free:</strong> 1-800-567-8934</strong>
                </div>
              </div>



              </div>
          </div>
        </div>

point_template/templates/cmstemplate/point/header1.html
{% extends "cmstemplate/point/base.html" %}
{% load cms_tags menu_tags sekizai_tags %}

{% block header %}
  {% placeholder header1 %}
{% endblock header %}

{% block base_content %}
  <div class="span8">
    {% placeholder content %}
  </div>
  <div class="span4">
    {% placeholder sidebar %}
  </div>
{% endblock base_content %}

point_template/templates/cmstemplate/point/header2.html
{% extends "cmstemplate/point/base.html" %}
{% load cms_tags menu_tags sekizai_tags %}

{% block header %}
  <div class="span6">
                  {% placeholder header1 %}
                </div>
                <div class="span6">
                  {% placeholder header2 %}
                </div>
{% endblock header %}

 
{% block base_content %}
  <div class="span8">
    {% placeholder content %}
  </div>
  <div class="span4">
    {% placeholder sidebar %}
  </div>
{% endblock base_content %}

point_template/templates/cmstemplate/point/header2a.html
{% extends "cmstemplate/point/base.html" %}
{% load cms_tags menu_tags sekizai_tags %}

{% block header %}
  <div class="span8">
                  {% placeholder header1 %}
                </div>
                <div class="span4">
                  {% placeholder header2 %}
                </div>
{% endblock header %}

 
{% block base_content %}
  <div class="span8">
    {% placeholder content %}
  </div>
  <div class="span4">
    {% placeholder sidebar %}
  </div>
{% endblock base_content %}

point_template/templates/cmstemplate/point/header3.html
{% extends "cmstemplate/point/base.html" %}
{% load cms_tags menu_tags sekizai_tags %}

{% block header %}
  <div class="span4">
    {% placeholder header1 %}
  </div>
  <div class="span4">
    {% placeholder header2 %}
  </div>
  <div class="span4">
    {% placeholder header3 %}
  </div>
{% endblock header %}

{% block base_content %}
  <div class="span8">
    {% placeholder content %}
  </div>
  <div class="span4">
    {% placeholder sidebar %}
  </div>
{% endblock base_content %}